ui: mocha-bdd
server: ./test/server.js
browserify:
  - transform:
      name: babelify
      sourceMaps: inline
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: iphone
    version: latest
  - name: android
    version: latest
  - name: ie
    version: 9..latest